### ISSUE TITLE
Review Current Move Induction Solutions

### ISSUE THREAD

**Issue by MatTheTab** [MatTheTab/PikeBot#5]
Check the code uploaded to utils and the notebook, make sure the implementations are correct, play some games or write unit tests, check if the proposed schema of designing the bots is sensible and if it works well. Most potentially dangerous places in the code comments denoted with "CHECK".

**Comment by Gho-Ost** [comment]
Added updates to chess_utils.py on tests branch, tests folder:
- OptimalStockFishAgent: fixed playing methods
- OptimalSimpleEngineAgent: limits setting by dict
- get_random_chessboard() - function generating a random chessboard state for testing

**Comment by Gho-Ost** [comment]
Initially approved, more complex tests could be done on a ready model
